version: '3.8'

services:
  redis:
    image: redis:7-alpine
    container_name: project-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      # Redis 데이터 영속성
      - ./redis/data:/data
      # Redis 설정 파일
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 10s
    networks:
      - redis-network

networks:
  redis-network:
    driver: bridge
